/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gnopvsdxhjhndrwoqqxq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub3B2c2R4aGpobmRyd29xcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjI1MjMsImV4cCI6MjA3NDQzODUyM30.JUr-N3kwHlOzbMKxkFRhr0kRT8-QYLMJLzwnPnVT9gc"